export const STREAM = {
  REQEUST_AUTH_URL: 'REQEUST_AUTH_URL',
};

export const AUTH = {
  LOAD_DATA: 'LOAD_AUTH_DATA',
  SET_CLIENTID: 'SET_CLIENTID',
  SET_AUTH_URL: 'SET_AUTH_URL',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  CLEAR_AUTH: 'CLEAR_AUTH',
};

export const MASTODON = {
  SET_MY_ACCOUNT: 'SET_MY_ACCOUNT',
  START_STREAM: 'START_STREAM',
  RESET_TOOTS: 'RESET_TOOTS',
  ADD_TOOTS: 'ADD_TOOTS',
  DELETE_TOOTS: 'DELETE_TOOTS',
  POST_TOOTS: 'POST_TOOTS',
  SET_BUSY: 'SET_BUSY',
  SET_FAVORITE: 'SET_FAVORITE',
  SET_BOOST: 'SET_BOOST',
  RESET_NOTIFICATION: 'RESET_NOTIFICATION',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  LOGOUT_MASTODON: 'LOGOUT_MASTODON',
};

export const COMPOSE = {
  UPDATE_TEXTAREA: 'UPDATE_TEXTAREA',
  ADD_TEXTAREA: 'ADD_TEXTAREA',
  CLEAR_TOOT: 'CLEAR_TOOT',
  SET_DEFAULT_VISIBLITY: 'SET_DEFAULT_VISIBLITY',
  SET_UPLOADING: 'SET_UPLOADING',
  ADD_ATTACH: 'ADD_ATTACH',
  DELETE_ATTACH: 'DELETE_ATTACH',
  TOGGLE_SENSITIVE: 'TOGGLE_SENSITIVE',
  CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
  UPDATE_SPOILER: 'UPDATE_SPOILER',
  TOGGLE_SPOILER: 'TOGGLE_SPOILER',
  MAKE_REPLY: 'MAKE_REPLY',
  CLEAR_REPLY: 'CLEAR_REPLY',
};
